import React,{useEffect,useMemo,useState} from "react";
import "./AdminDashboard.css";
import {supabase} from "./supabase.js";

const nav=[["overview","Overview"],["users","Users"],["visitors","Web Visitors"],["games","FLAMES Games"],["questions","Questions"],["feedback","Feedback"],["activity","Activity"],["announcements","Announcements"]];

const fmt=(n)=>new Intl.NumberFormat().format(Number(n||0));
const time=(v)=>v?new Date(v).toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):"—";

export default function AdminDashboard(){
 const [admin,setAdmin]=useState(null),[loading,setLoading]=useState(true),[page,setPage]=useState("overview"),[range,setRange]=useState(7),[data,setData]=useState({}),[users,setUsers]=useState([]),[visitors,setVisitors]=useState([]),[games,setGames]=useState([]),[questions,setQuestions]=useState([]),[feedback,setFeedback]=useState([]),[activity,setActivity]=useState([]),[announcements,setAnnouncements]=useState([]),[search,setSearch]=useState(""),[menu,setMenu]=useState(false),[error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const r=await supabase.from("flames_admin_users").select("user_id,role").eq("user_id",user.id).single();if(r.error||!r.data){setLoading(false);setError("This account does not have admin access.");return}setAdmin({user,role:r.data.role});setLoading(false)})()},[]);
 const load=async()=>{if(!admin)return;setError("");const [u,v,g,q,f,a,n]=await Promise.all([
   supabase.from("flames_profiles").select("*").order("created_at",{ascending:false}).limit(200),
   supabase.from("flames_analytics_events").select("*").order("created_at",{ascending:false}).limit(500),
   supabase.from("flames_matches").select("*").order("created_at",{ascending:false}).limit(200),
   supabase.from("flames_games").select("*").order("created_at",{ascending:false}).limit(200),
   supabase.from("flames_feedback").select("*").order("created_at",{ascending:false}).limit(100),
   supabase.from("flames_admin_activity").select("*").order("created_at",{ascending:false}).limit(100),
   supabase.from("flames_admin_announcements").select("*").order("created_at",{ascending:false}).limit(50)
 ]); if(u.error||v.error||g.error||q.error||f.error){setError((u.error||v.error||g.error||q.error||f.error)?.message||"Unable to load admin data.");return}
 setUsers(u.data||[]);setVisitors(v.data||[]);setGames(g.data||[]);setQuestions(q.data||[]);setFeedback(f.data||[]);setActivity(a.data||[]);setAnnouncements(n.data||[]);
 const ev=v.data||[];const visitorIds=new Set(ev.map(x=>x.visitor_id).filter(Boolean));const today=new Date();today.setHours(0,0,0,0);
 const timeline=Array.from({length:range},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(range-1-i));const end=new Date(d);end.setDate(end.getDate()+1);return {day:d,visitors:new Set(ev.filter(x=>{const t=new Date(x.created_at);return t>=d&&t<end&&x.visitor_id}).map(x=>x.visitor_id)).size,games:(g.data||[]).filter(x=>new Date(x.created_at)>=d&&new Date(x.created_at)<end).length,signups:(u.data||[]).filter(x=>new Date(x.created_at)>=d&&new Date(x.created_at)<end).length}});
 setData({realUsers:(u.data||[]).length,webUniqueIds:visitorIds.size,activeToday:new Set(ev.filter(x=>new Date(x.created_at)>=today).map(x=>x.visitor_id||x.session_id)).size,newUsersToday:(u.data||[]).filter(x=>new Date(x.created_at)>=today).length,gamesTotal:(g.data||[]).length,gamesToday:(g.data||[]).filter(x=>new Date(x.created_at)>=today).length,questionsTotal:(q.data||[]).length,questionsToday:(q.data||[]).filter(x=>new Date(x.created_at)>=today).length,feedbackTotal:(f.data||[]).length,feedbackOpen:(f.data||[]).filter(x=>x.status!=="resolved").length,timeline,modes:{classic:(g.data||[]).filter(x=>!x.secret_mode).length,secret:(g.data||[]).filter(x=>x.secret_mode).length}})};
 useEffect(()=>{load()},[admin,range]);
 const filtered=(rows,fields)=>rows.filter(r=>!search||fields.some(k=>String(r[k]??"").toLowerCase().includes(search.toLowerCase())));
 if(loading)return <div className="admin-empty">Checking admin access…</div>;
 if(!admin)return <div className="admin-empty"><strong>{error||"Admin access required."}</strong><div style={{marginTop:8}}>Sign in with the administrator account, then open /admin.</div></div>;
 const max=Math.max(1,...(data.timeline||[]).map(x=>x.visitors));
 return <div className="admin-shell">
  <aside className={"admin-sidebar "+(menu?"open":"")}><div className="admin-brand">FLAMES <span>ADMIN</span></div><nav className="admin-nav">{nav.map(([id,label])=><button className={page===id?"active":""} onClick={()=>{setPage(id);setMenu(false)}} key={id}>{label}</button>)}</nav><div className="admin-sidebar-foot">Role: {admin.role}<br/>Protected by Supabase Auth + RLS</div></aside>
  <main className="admin-main"><header className="admin-top"><div><button className="admin-btn admin-mobile-toggle" onClick={()=>setMenu(!menu)}>Menu</button><div className="admin-kicker">FLAMES CONTROL CENTER</div><h1 className="admin-title">{nav.find(x=>x[0]===page)?.[1]||"Overview"}</h1></div><div className="admin-top-actions"><select className="admin-select" value={range} onChange={e=>setRange(Number(e.target.value))}><option value="1">Today</option><option value="7">7 days</option><option value="30">30 days</option></select><button className="admin-btn" onClick={load}>Refresh</button></div></header>
  {error&&<div className="admin-card" style={{marginBottom:14}}>{error}</div>}
  {page==="overview"&&<><section className="admin-grid">
   {[["Real Users",data.realUsers,"registered accounts"],["Web Unique IDs",data.webUniqueIds,"unique visitor IDs"],["Active Today",data.activeToday,"visitor/session activity"],["Games Played",data.gamesTotal,"saved matches"],["Games Today",data.gamesToday,"today"],["Questions",data.questionsTotal,"created games"],["New Users Today",data.newUsersToday,"signups"],["Open Feedback",data.feedbackOpen,"needs review"]].map(x=><div className="metric" key={x[0]}><div className="metric-label">{x[0]}</div><div className="metric-value">{fmt(x[1])}</div><div className="metric-note">{x[2]}</div></div>)}
  </section><section className="admin-two"><div className="admin-card"><div className="admin-card-head"><h3>Visitor activity</h3><span className="legend">{range} day window</span></div><div className="chart">{(data.timeline||[]).map((x,i)=><div className="bar-wrap" key={i}><div style={{width:"100%"}}><div className="bar" style={{height:Math.max(4,(x.visitors/max)*160)}}/><div className="bar-label">{x.day.toLocaleDateString([],{weekday:"narrow"})}</div></div></div>)}</div></div>
   <div className="admin-card"><h3>Game mix</h3><div className="admin-list"><div className="admin-row"><div><strong>Classic FLAMES</strong><small>Standard matching</small></div><span className="pill">{fmt(data.modes?.classic)}</span></div><div className="admin-row"><div><strong>Secret Crush</strong><small>Private mode</small></div><span className="pill">{fmt(data.modes?.secret)}</span></div><div className="admin-row"><div><strong>Feedback</strong><small>Open / reviewing</small></div><span className="pill">{fmt(data.feedbackOpen)}</span></div></div></div>
  </div></>}
  {page==="users"&&<Table title="Registered users" search={search} setSearch={setSearch} rows={filtered(users,["username","display_name","id"])} cols={["username","display_name","id","created_at","last_active_date"]} labels={["Username","Name","User ID","Joined","Last active"]}/>}
  {page==="visitors"&&<Table title="Recent web activity" search={search} setSearch={setSearch} rows={filtered(visitors,["visitor_id","session_id","event_name","path","device_type"])} cols={["event_name","visitor_id","session_id","path","device_type","created_at"]} labels={["Event","Web ID","Session","Path","Device","Time"]}/>}
  {page==="games"&&<Table title="FLAMES matches" search={search} setSearch={setSearch} rows={filtered(games,["name_a","name_b","result_key"])} cols={["name_a","name_b","result_key","percent","secret_mode","created_at"]} labels={["Name A","Name B","Result","%","Mode","Played"]}/>}
  {page==="questions"&&<Table title="Created questions" search={search} setSearch={setSearch} rows={filtered(questions,["title","prompt","kind"])} cols={["title","kind","prompt","created_at","expires_at"]} labels={["Title","Type","Prompt","Created","Expires"]}/>}
  {page==="feedback"&&<Table title="Feedback inbox" search={search} setSearch={setSearch} rows={filtered(feedback,["category","rating","message","status"])} cols={["rating","category","message","status","created_at"]} labels={["Rating","Category","Message","Status","Received"]}/>}
  {page==="activity"&&<Table title="Admin activity" search={search} setSearch={setSearch} rows={filtered(activity,["action","target_type","target_id"])} cols={["action","target_type","target_id","created_at"]} labels={["Action","Target","ID","Time"]}/>}
  {page==="announcements"&&<div className="admin-card"><h3>Announcements</h3>{announcements.length?<div className="admin-list">{announcements.map(a=><div className="admin-row" key={a.id}><div><strong>{a.title}</strong><small>{a.body}</small></div><span className="pill">{a.active?"ACTIVE":"OFF"}</span></div>)}</div>:<div className="admin-empty">No announcements yet.</div>}</div>}
  </main></div>
}
function Table({title,rows,cols,labels,search,setSearch}){return <div className="admin-card admin-table-card"><div className="admin-toolbar"><h3>{title}</h3><input className="admin-search" placeholder="Search…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="admin-table-wrap">{rows.length?<table className="admin-table"><thead><tr>{labels.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{c==="created_at"||c==="expires_at"?time(r[c]):c==="secret_mode"?(r[c]?"Secret Crush":"Classic"):String(r[c]??"—")}</td>)}</tr>)}</tbody></table>:<div className="admin-empty">No matching records.</div>}</div></div>}
